{
    "alwaysDetachLogger":false,
    "selectedFilterLists":[
        "ublock-filters"
    ],
    "contextMenuEnabled":true,
    "prefetchingDisabled":true,
    "hostnameSwitchesString":"",
    "largeMediaSize":50,
    "hyperlinkAuditingDisabled":true,
    "externalLists":"",
    "advancedUserEnabled":false,
    "allowedRequestCount":737,
    "selfieMagic":"pwvcdyqfkuek",
    "ignoreGenericCosmeticFilters":false,
    "availableFilterLists":{
        "double_verify-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/double_verify-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"double_verify-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "alphabet-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/alphabet-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"alphabet-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "facebook-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/facebook-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"facebook-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "facebook-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/facebook-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"facebook-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "yandex-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/yandex-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"yandex-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "pubmatic-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/pubmatic-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"pubmatic-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "yandex-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/yandex-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"yandex-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "adobe_systems-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/adobe_systems-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"adobe_systems-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "adobe_systems-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/adobe_systems-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"adobe_systems-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "verizon-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/verizon-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"verizon-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "alphabet-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/alphabet-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"alphabet-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "verizon-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/verizon-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"verizon-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "exoclick-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/exoclick-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"exoclick-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "appnexus-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/appnexus-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"appnexus-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "alibaba-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/alibaba-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"alibaba-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "integral_ad_science-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/integral_ad_science-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"integral_ad_science-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "twitter-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/twitter-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"twitter-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "appnexus-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/appnexus-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"appnexus-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "baidu-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/baidu-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"baidu-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "sovrn-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/sovrn-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"sovrn-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "quantcast-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/quantcast-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"quantcast-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "integral_ad_science-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/integral_ad_science-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"integral_ad_science-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "automattic-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/automattic-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"automattic-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "criteo-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/criteo-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"criteo-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "automattic-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/automattic-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"automattic-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "double_verify-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/double_verify-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"double_verify-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "baidu-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/baidu-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"baidu-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "microsoft-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/microsoft-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"microsoft-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "criteo-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/criteo-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"criteo-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "twitter-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/twitter-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"twitter-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "ublock-filters":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/alphabet-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"ublock filters",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1546307101,
            "updateAfter":5,
            "off":false
        },
        "pubmatic-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/pubmatic-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"pubmatic-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "alibaba-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/alibaba-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"alibaba-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "oracle-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/oracle-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"oracle-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "sovrn-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/sovrn-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"sovrn-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "exoclick-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/exoclick-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"exoclick-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "microsoft-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/microsoft-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"microsoft-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "oracle-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/oracle-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"oracle-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "comscore-some-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/comscore-some.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"comscore-some-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "comscore-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/comscore-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"comscore-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        },
        "quantcast-all-filter":{
            "contentURL":[
                "/home/johncook/headerBidding/TrackingProject/src/ent_abp/quantcast-all.txt"
            ],
            "remoteURL":"",
            "entryUsedCount":0,
            "hasLocalURL":true,
            "cached":true,
            "hasRemoteURL":false,
            "supportURL":"",
            "title":"quantcast-all-filter",
            "obsolete":false,
            "content":"filters",
            "entryCount":0,
            "group":"default",
            "writeTime":1547618662,
            "updateAfter":5,
            "off":false
        }
    },
    "collapseBlocked":true,
    "dynamicFilteringEnabled":false,
    "version":"1.14.10",
    "firewallPaneMinimized":true,
    "autoUpdate":false,
    "requestLogMaxEntries":1000,
    "remoteBlacklists":{},
    "showIconBadge":true,
    "parseAllABPHideFilters":false,
    "colorBlindFriendly":false,
    "filterLists":{
        "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains":{
            "off":false
        },
        "assets/thirdparties/pgl.yoyo.org/as/serverlist":{
            "off":true
        },
        "assets/user/filters.txt":{
            "off":true
        },
        "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt":{
            "off":true
        },
        "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt":{
            "off":true
        },
        "assets/ublock/unbreak.txt":{
            "off":true
        },
        "assets/ublock/privacy.txt":{
            "off":true
        },
        "assets/ublock/filters.txt":{
            "off":false
        },
        "assets/ublock/experimental.txt":{
            "off":true
        },
        "assets/ublock/badware.txt":{
            "off":true
        },
        "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt":{
            "off":true
        }
    },
    "urlFilteringString":"",
    "compiledMagic":"pwvcdyqfkuek",
    "blockedRequestCount":191,
    "webrtcIPAddressHidden":false,
    "tooltipsDisabled":true,
    "cloudStorageEnabled":false,
    "netWhitelist":"",
    "userFilters":""
}